# Generated by Django 3.0.8 on 2020-07-26 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(default='SOME STRING', max_length=50)),
                ('gfather', models.CharField(default='SOME STRING', max_length=60)),
                ('name', models.CharField(default='SOME STRING', max_length=50)),
                ('gaddress', models.CharField(default='SOME STRING', max_length=250)),
                ('bname', models.CharField(default='SOME STRING', max_length=50)),
                ('bfather', models.CharField(default='SOME STRING', max_length=50)),
                ('baddress', models.CharField(default='SOME STRING', max_length=250)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
