# Generated by Django 2.0.2 on 2020-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FORM', '0002_auto_20200830_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='rdate',
            field=models.CharField(default='SOME STRING', max_length=16),
        ),
    ]
