# Generated by Django 3.1.1 on 2020-09-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FORM', '0003_form_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='rdate',
            field=models.DateField(),
        ),
    ]
