# Generated by Django 3.1.1 on 2020-12-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FORM', '0004_auto_20200902_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
